import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Closette",
};

const EFFECTIVE_DATE = "April 19, 2026";
const OPERATOR = "9537-1076 Quebec Inc.";
const CONTACT_EMAIL = "alex@automatable.co";

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-12 text-sm leading-relaxed">
      <h1 className="font-[family-name:var(--font-heading)] text-3xl mb-2">
        Terms of Service
      </h1>
      <p className="text-muted-foreground mb-8">
        Effective {EFFECTIVE_DATE}
      </p>

      <p className="mb-6">
        These Terms of Service (the &quot;Terms&quot;) govern your access to
        and use of Closette, operated by <strong>{OPERATOR}</strong>
        (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;). By creating an
        account or using Closette, you agree to these Terms.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">1. Eligibility</h2>
      <p className="mb-6">
        You must be at least 13 years old to use Closette. If you are under
        the age of majority where you live, you must have your parent or
        guardian&apos;s permission.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">2. Your account</h2>
      <ul className="list-disc pl-5 space-y-2 mb-6">
        <li>
          You are responsible for keeping your password secure and for
          activity under your account.
        </li>
        <li>Provide accurate information when you sign up.</li>
        <li>Do not share your account with others.</li>
        <li>
          Notify us immediately at{" "}
          <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>
            {CONTACT_EMAIL}
          </a>{" "}
          if you suspect unauthorized access.
        </li>
      </ul>

      <h2 className="font-semibold text-lg mt-8 mb-3">3. Your content</h2>
      <p className="mb-3">
        Closette lets you upload photos and information about your clothes
        (&quot;User Content&quot;). You retain all rights to your User
        Content. By uploading, you grant us a limited, non-exclusive,
        royalty-free license to store, display, and process your User
        Content solely to operate the service for you.
      </p>
      <p className="mb-6">
        You are responsible for your User Content and for ensuring you have
        the right to upload it. Do not upload content that is illegal,
        infringes on others&apos; rights, or contains sensitive personal
        information about other people.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">4. Acceptable use</h2>
      <p className="mb-3">You agree not to:</p>
      <ul className="list-disc pl-5 space-y-2 mb-6">
        <li>Use the service for any unlawful purpose.</li>
        <li>
          Attempt to access other users&apos; accounts or data, or interfere
          with security.
        </li>
        <li>Reverse-engineer, scrape, or resell the service.</li>
        <li>Upload malware, spam, or abusive content.</li>
        <li>Abuse the AI features (e.g., prompt injection, automated scraping).</li>
      </ul>

      <h2 className="font-semibold text-lg mt-8 mb-3">5. AI-generated suggestions</h2>
      <p className="mb-6">
        Outfit and packing suggestions are generated by a third-party AI
        model. They are provided for convenience and may contain
        inaccuracies or unsuitable recommendations. Use your own judgment.
        We disclaim any liability for styling choices or outcomes based on
        AI output.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">6. Subscriptions and fees</h2>
      <p className="mb-6">
        Closette may introduce paid subscription plans in the future. Fees,
        billing terms, and cancellation policies will be presented before
        any charge. Until then, access is provided free of charge.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">7. Service changes & availability</h2>
      <p className="mb-6">
        We may modify, suspend, or discontinue features at any time. We
        don&apos;t guarantee the service will be uninterrupted or error-free.
        Scheduled or emergency maintenance may cause downtime.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">8. Termination</h2>
      <p className="mb-6">
        You may delete your account at any time. We may suspend or
        terminate your account if you violate these Terms or engage in
        abusive behavior. On termination, your right to use the service
        ends and we will delete your data in accordance with our{" "}
        <Link href="/privacy" className="underline">
          Privacy Policy
        </Link>
        .
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">9. Disclaimers</h2>
      <p className="mb-6 uppercase text-xs tracking-wide">
        The service is provided &quot;as is&quot; and &quot;as available&quot;,
        without warranties of any kind, whether express, implied, statutory,
        or otherwise, including merchantability, fitness for a particular
        purpose, or non-infringement.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">10. Limitation of liability</h2>
      <p className="mb-6 uppercase text-xs tracking-wide">
        To the maximum extent permitted by law, {OPERATOR} and its
        affiliates, officers, employees, and agents shall not be liable for
        any indirect, incidental, consequential, special, exemplary, or
        punitive damages arising out of or related to your use of the
        service. Our total aggregate liability for any claim shall not
        exceed CAD $100 or the amount you paid us in the preceding 12
        months, whichever is greater.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">11. Indemnification</h2>
      <p className="mb-6">
        You agree to indemnify and hold harmless {OPERATOR} from any claims
        arising out of your User Content, your use of the service, or your
        violation of these Terms.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">12. Governing law</h2>
      <p className="mb-6">
        These Terms are governed by the laws of the Province of Quebec and
        the applicable laws of Canada. Exclusive jurisdiction for any
        dispute lies with the courts of the judicial district of Montreal,
        Quebec, except where prohibited by mandatory local consumer law.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">13. Changes to the Terms</h2>
      <p className="mb-6">
        We may update these Terms from time to time. Material changes will
        be announced in-app or by email. Continued use after a change
        constitutes acceptance.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">14. Contact</h2>
      <p className="mb-6">
        Questions? Email{" "}
        <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>
          {CONTACT_EMAIL}
        </a>
        .
      </p>

      <div className="mt-12 flex gap-6 text-sm">
        <Link href="/privacy" className="underline">
          Privacy Policy
        </Link>
        <Link href="/login" className="underline">
          Back to sign in
        </Link>
      </div>
    </div>
  );
}
