import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — Closette",
};

const EFFECTIVE_DATE = "April 19, 2026";
const OPERATOR = "9537-1076 Quebec Inc.";
const CONTACT_EMAIL = "alex@automatable.co";

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-12 text-sm leading-relaxed">
      <h1 className="font-[family-name:var(--font-heading)] text-3xl mb-2">
        Privacy Policy
      </h1>
      <p className="text-muted-foreground mb-8">
        Effective {EFFECTIVE_DATE}
      </p>

      <section className="space-y-4 mb-8">
        <p>
          Closette (&quot;Closette&quot;, &quot;we&quot;, &quot;us&quot;,
          &quot;our&quot;) is operated by <strong>{OPERATOR}</strong>, a
          corporation formed under the laws of the Province of Quebec, Canada.
          This Privacy Policy explains what information we collect, how we use
          it, and the choices you have.
        </p>
        <p>
          By creating an account or using Closette, you agree to this Privacy
          Policy. If you do not agree, please do not use the service.
        </p>
      </section>

      <h2 className="font-semibold text-lg mt-8 mb-3">1. Information we collect</h2>
      <ul className="list-disc pl-5 space-y-2 mb-6">
        <li>
          <strong>Account information:</strong> email address and password
          (stored as a salted hash by our authentication provider).
        </li>
        <li>
          <strong>Wardrobe content you provide:</strong> photos of clothing
          items, item names, categories, colors, brands, notes, and related
          metadata you enter.
        </li>
        <li>
          <strong>Usage data:</strong> outfits you create, wear history you
          log, preferences you set (temperature sensitivity, preferred colors,
          styles).
        </li>
        <li>
          <strong>Location (optional):</strong> if you grant permission, we
          use your approximate location to fetch local weather for outfit
          recommendations. Location is stored only as a coordinate + city name
          on your profile.
        </li>
        <li>
          <strong>Technical data:</strong> standard server logs (IP address,
          user agent, timestamps) for security and debugging.
        </li>
      </ul>

      <h2 className="font-semibold text-lg mt-8 mb-3">2. How we use your information</h2>
      <ul className="list-disc pl-5 space-y-2 mb-6">
        <li>Provide, personalize, and improve the service.</li>
        <li>
          Generate AI-powered outfit suggestions using your wardrobe and
          preferences (see &quot;AI processing&quot; below).
        </li>
        <li>Authenticate you and secure your account.</li>
        <li>
          Communicate service-related messages (e.g., email verification,
          password resets). We do not send marketing emails.
        </li>
      </ul>

      <h2 className="font-semibold text-lg mt-8 mb-3">3. AI processing</h2>
      <p className="mb-6">
        Outfit suggestions and packing lists are generated by sending your
        wardrobe metadata (not your photos) to a large language model
        operated by Anthropic, PBC. Photos themselves are not sent to the
        AI. The AI provider processes this data as a sub-processor bound by
        contractual data-protection obligations.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">4. Where your data lives</h2>
      <ul className="list-disc pl-5 space-y-2 mb-6">
        <li>
          <strong>Application data</strong> (accounts, clothing items,
          outfits) is stored by <strong>Supabase Inc.</strong> in the United
          States.
        </li>
        <li>
          <strong>Photos</strong> are stored in object storage operated by{" "}
          <strong>Vercel Inc.</strong> and <strong>Supabase Inc.</strong>
        </li>
        <li>
          We use row-level security so each user can only access their own
          data.
        </li>
      </ul>

      <h2 className="font-semibold text-lg mt-8 mb-3">5. Data sharing</h2>
      <p className="mb-6">
        We do not sell your personal information. We share data only with
        service providers acting as sub-processors strictly to operate the
        service (Supabase, Vercel, Anthropic). We may disclose information if
        required by law or to protect the rights, property, or safety of
        users or the public.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">6. Your rights</h2>
      <p className="mb-3">
        Subject to applicable law (including Quebec Law 25, the GDPR, and the
        CPRA), you may:
      </p>
      <ul className="list-disc pl-5 space-y-2 mb-6">
        <li>Request access to the personal information we hold about you.</li>
        <li>Request correction of inaccurate information.</li>
        <li>Request deletion of your account and associated data.</li>
        <li>Export your data in a portable format.</li>
        <li>Withdraw consent for optional data collection (e.g., location).</li>
      </ul>
      <p className="mb-6">
        Contact us at{" "}
        <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>
          {CONTACT_EMAIL}
        </a>{" "}
        to exercise these rights. We will respond within 30 days.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">7. Data retention</h2>
      <p className="mb-6">
        We retain your account data for as long as your account is active.
        When you delete your account, we delete your personal data within 30
        days, except where retention is required by law.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">8. Security</h2>
      <p className="mb-6">
        We use industry-standard measures, including encryption in transit
        (HTTPS), encryption at rest (via Supabase and Vercel), and database
        row-level security. No system is perfectly secure; you use the
        service at your own risk.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">9. Children</h2>
      <p className="mb-6">
        Closette is not directed to children under 13. We do not knowingly
        collect personal information from children under 13. If you believe a
        child has provided us personal information, please contact us and we
        will delete it.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">10. Changes</h2>
      <p className="mb-6">
        We may update this Privacy Policy from time to time. Material changes
        will be announced in-app or by email. Continued use after a change
        constitutes acceptance.
      </p>

      <h2 className="font-semibold text-lg mt-8 mb-3">11. Contact</h2>
      <p className="mb-6">
        Questions about this Privacy Policy? Email{" "}
        <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>
          {CONTACT_EMAIL}
        </a>
        .
      </p>

      <div className="mt-12 flex gap-6 text-sm">
        <Link href="/terms" className="underline">
          Terms of Service
        </Link>
        <Link href="/login" className="underline">
          Back to sign in
        </Link>
      </div>
    </div>
  );
}
